/* include/abi/task_enums.h */
#ifndef _TASK_ENUMS_H
#define _TASK_ENUMS_H

typedef enum _TASK_TYPE {
    TASK_TYPE_ENCODE = 0,
    TASK_TYPE_DECODE = 1,
} _TASK_TYPE;

typedef enum _TASK_STATE {
    TASK_STATE_IDLE = 0,
    TASK_STATE_RUNNING = 1,
    TASK_STATE_PAUSED = 2,
} _TASK_STATE;

typedef enum _TASK_DATA_TYPE {
    TASK_DATA_TYPE_VIDEO = 0,
    TASK_DATA_TYPE_AUDIO = 1,
    TASK_DATA_TYPE_VBI = 2,
    TASK_DATA_TYPE_RAW_VIDEO = 3,
    TASK_DATA_TYPE_RAW_AUDIO = 4,
    TASK_DATA_TYPE_TS = 5,
    TASK_DATA_TYPE_SUBPIC = 6,
} _TASK_DATA_TYPE;

typedef enum _CHANNEL_DIRECTION {
    CHANNEL_DIRECTION_IN = 0,
    CHANNEL_DIRECTION_OUT = 1,
} _CHANNEL_DIRECTION;

typedef enum _FIRMWARE_DATA_TYPE {
    FIRMWARE_DATA_TYPE_UNKNOWN = 0,
} _FIRMWARE_DATA_TYPE;

#endif /* _TASK_ENUMS_H */
